### ISSUE TITLE
There is no way to set a description for "Available providers" screen

### ISSUE THREAD

**Issue by revanmj** [levelup/palabre-extensions#1]
As in the title, I don't see any way to set an extensions descritpion for "Available providers" screen and it looks a little odd without it. You can see what I mean in the attached screenshot.

![screenshot_20151210-212118](https://cloud.githubusercontent.com/assets/1777618/11727493/6101b258-9f84-11e5-98dc-4b947cff2b4d.png)

**Comment by lvialle** [comment]
This description come from a json file from our server for the featured extensions. We will gladly add your extension to the featured extensions, and the description you provide, once it is release :)

**Comment by revanmj** [comment]
OK, I'll let you know after release then. But I think it's worth mentioning in the repo's readme file so any other interest devs will know about it :)

**Comment by revanmj** [comment]
Here it is: [Feedbin for Palabre Beta](https://play.google.com/store/apps/details?id=pl.revanmj.feedbinforpalabre) and I think standard description will suffice ("Add your Feedbin account in Palabre and enjoy reading articles").

**Comment by lvialle** [comment]
Thanks! We will give it a try just to make sure it works, and we will add it to our featured list.

Great job!

**Comment by lvialle** [comment]
We tested it and it works perfectly. Can you provide the icon in a 512x512 png with transparent background format please?

**Comment by revanmj** [comment]
Sure, here it is: https://dl.dropboxusercontent.com/u/1561186/ic_launcher-web.png

**Comment by lvialle** [comment]
There, it's displayed within the app. Thanks for your extension!

**Comment by revanmj** [comment]
You're welcome and thanks for featuring it in your app :)

pt., 11.03.2016, 09:35 użytkownik Ludovic Vialle notifications@github.com
napisał:
